### ISSUE TITLE
#108 - backend: rename Auditor

### ISSUE THREAD

**Issue by solairerove** [vlsidlyarevich/unity#108]
rename [Auditor](https://github.com/vlsidlyarevich/unity/blob/master/src/main/java/com/github/vlsidlyarevich/unity/common/audit/Auditor.java) to Auditing

**Comment by vlsidlyarevich** [comment]
@solairerove  Why?

**Comment by solairerove** [comment]
auditor is name for class, not for interface

**Comment by vlsidlyarevich** [comment]
@solairerove  and?

**Comment by solairerove** [comment]
![image](https://user-images.githubusercontent.com/9396988/30427263-cfd8c85a-9957-11e7-852c-c10e96b0dc1f.png)

**Comment by vlsidlyarevich** [comment]
@solairerove  lol, dat eng
