### ISSUE TITLE
#109 - backend: AnalysisReport switch/case

### ISSUE THREAD

**Issue by solairerove** [vlsidlyarevich/unity#109]
[AnalysisReport](https://github.com/vlsidlyarevich/unity/blob/master/src/main/java/com/github/vlsidlyarevich/unity/common/model/AnalysisReport.java) use `switch/case` statement cause of more than two `if/else`

- maybe final fields/nevermind

**Comment by vlsidlyarevich** [comment]
@solairerove In java switch over instanceof is weird : 
https://stackoverflow.com/questions/29570767/switch-over-type-in-java
