### ISSUE TITLE
#112 - backend: checkstyle/pmd/findbugs/jacoco

### ISSUE THREAD

**Issue by solairerove** [vlsidlyarevich/unity#112]

**Comment by vlsidlyarevich** [comment]
@solairerove  I already have checkstyle, pmd, jacoco.

**Comment by solairerove** [comment]
so why u don't have any java dick(doc)

**Comment by vlsidlyarevich** [comment]
@solairerove  i have decided to remove such violation, at the moment i don't need javadocs
