### ISSUE TITLE
#118 - backend: ConfigurableRestTemplateFactory

### ISSUE THREAD

**Issue by solairerove** [vlsidlyarevich/unity#118]
to configuration with normal rest template bean config

![image](https://user-images.githubusercontent.com/9396988/30427533-d66f5ac0-9958-11e7-9cd5-7754641af27a.png)

**Comment by solairerove** [comment]
фактори кусок говна. тут настройка лайк спринг стайл

**Comment by vlsidlyarevich** [comment]
будешь пиздеть на интерпраез паттерны, получишь пизды!

**Comment by vlsidlyarevich** [comment]
Этот рест темплейт сразу с нужными хедерами для запросов к гиту, если его регать как бин, то будет хуёво, когда я захочу обычный рест темплейт и приавтоварю сразу этот.
