### ISSUE TITLE
#119 - backend: Refactor git models

### ISSUE THREAD

**Issue by solairerove** [vlsidlyarevich/unity#119]
![image](https://user-images.githubusercontent.com/9396988/30427741-975e41d8-9959-11e7-8e31-555eeca43938.png)

repeated fields abstract to pojos

**Comment by solairerove** [comment]
вынеси поля одинаковые в модели.

**Comment by vlsidlyarevich** [comment]
Не выйдет, одна модель для сериализации, там дохуя аннотаций.
