### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by akraskovski** [vlsidlyarevich/unity#128]
Get Data Controller, Service, Repository, Model and dto.
Model should contain field: data.
Realize endpoints:
- Get data (HTTP: GET)

Please add validation on data field. data must be only data format.

**Comment by solairerove** [comment]
@akraskovski i suggest u to add some details, like as `private final Data data`

**Comment by akraskovski** [comment]
@solairerove you are right. but when @vlsidlyarevich will add the field `Data` he also need to override Equals and Hashcode methods.
I think, that it will looks like `if (this.data == Object.data) {
return true;
}
`

**Comment by vlsidlyarevich** [comment]
Also, i need DataRepository, DataService with DataDataService which implements Datable interface. Also i need Data2DataDto converter. Exception handling is based on data exceptions from data components.

**Comment by akraskovski** [comment]
And of course! don't forget to use `finalize` method from Object class. because `Data` if very heavyweight object, so you need to tell GC when to clean it.

**Comment by solairerove** [comment]
сколько можно флудить

**Comment by vlsidlyarevich** [comment]
@akraskovski  your seniority in the field of JVM and GC is wonderful. I will do this according to your suggestion! Also, because it is a SpringBoot project we need to boot our binz from app context. Annotations are heavyweight, so, i will not use them. And after using the bean it needs to be finalized.

**Comment by akraskovski** [comment]
@vlsidlyarevich you are not right. in project with Data functionallity you have really need to use Spring?
I think, that clean Java 1.2 can provide you all possibilities to finish this issue.

**Comment by solairerove** [comment]
last 20 years i developed super heavy load weight project and suggest u to write static util classes
