### ISSUE TITLE
Code Permission 

### ISSUE THREAD

**Issue by waqaskamran** [vlsidlyarevich/unity#141]
can i get your code for practice . I am stuck with jwt and spring social . thanks

**Comment by vlsidlyarevich** [comment]
@sayjavajava no problems, you can use my code for research and practice. I hope it will help you, please star it if it help you.

**Comment by waqaskamran** [comment]
thanks . sure i will start it .

I am getting an issue while "mvn clean install" .

*issue *" Error at Typings ......." (related to Angular node module )

can you check your pom and angular dependencies again and commit thanks

**Comment by vlsidlyarevich** [comment]
@sayjavajava  please, install typings globally via `npm install typings -g`

**Comment by waqaskamran** [comment]
thanks
