### ISSUE TITLE
#35 - lombok @data

### ISSUE THREAD

**Issue by solairerove** [vlsidlyarevich/unity#35]
[see](https://github.com/vlsidlyarevich/unity/blob/master/src/main/java/com/github/vlsidlyarevich/unity/model/Name.java)
data already have equals and hashcode. it has to string too. Watch source code

**Comment by solairerove** [comment]
https://github.com/vlsidlyarevich/unity/blob/master/src/main/java/com/github/vlsidlyarevich/unity/model/Name.java

**Comment by vlsidlyarevich** [comment]
ok, thx
