### ISSUE TITLE
#46 - organize deploy on heroku ( add docker-compose and procfile )

### ISSUE THREAD

**Issue by vlsidlyarevich** [vlsidlyarevich/unity#46]

**Comment by solairerove** [comment]
easy

**Comment by vlsidlyarevich** [comment]
@solairerove please, contact me when you will be free to help

**Comment by solairerove** [comment]
ok. I think about adding some post in our future blog, instead of boilerplate repos with this shit configs and else. such as deploy boot on heroku.
