### ISSUE TITLE
#75 - backend: refactoring

### ISSUE THREAD

**Issue by vlsidlyarevich** [vlsidlyarevich/unity#75]
Remove @Override, praise the java
Remove impl folder, move implementations to the interfaces, praise the java
Remove unused methods and it's implementations, praise the java and @solairerove  
Rename "Simpl" to "Default" or "Basic", praise the java and @KarpukDm  
Move version to properties in pom.xml
Add "/" to all urls in controllers (just for now there are urls with "/" and without, it is needed to be in one way)
Send 204 on http delete
Fixme -> TODO and description
All null checks should be on service layer, not controller layer
Don't use string concatenation in that way ""+"", use Sl4fj templates instead

IF THERE IS IN POCKET MEMES, THEN TOMOROW THERE WILL BE NO PROBLEMES (c)

**Comment by solairerove** [comment]
praise the sun, praise solairerove, praise me

**Comment by vlsidlyarevich** [comment]
@solairerove AVE SUN, AVE @solairerove
